version: "3.7"

services:
  bot:
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - bot-net
    restart: always

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - bot-net


networks:
  bot-net:

volumes:
  postgres_data:
