version: "3.7"

services:
  bot:
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - bot-net
    restart: always

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: event_bot
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - bot-net


networks:
  bot-net:

volumes:
  postgres_data:
