"""Add base model fields

Revision ID: 0e27d2923d83
Revises: 1ef2f25b59d2
Create Date: 2025-06-23 23:41:29.454827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e27d2923d83'
down_revision = '1ef2f25b59d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactive_history', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('interactive_history', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('Europe/Moscow', now())"), nullable=False))
    op.add_column('interactive_history', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('Europe/Moscow', now())"), nullable=False))
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('user', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('Europe/Moscow', now())"), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('Europe/Moscow', now())"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'is_active')
    op.drop_column('interactive_history', 'updated_at')
    op.drop_column('interactive_history', 'created_at')
    op.drop_column('interactive_history', 'is_active')
    # ### end Alembic commands ### 