"""update_interactive_history_foreign_key

Revision ID: 4cdcc72cf980
Revises: 0e27d2923d83
Create Date: 2025-06-24 17:09:43.448954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cdcc72cf980'
down_revision = '0e27d2923d83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Удаляем старую foreign key связь
    op.drop_constraint('interactive_history_user_id_fkey', 'interactive_history', type_='foreignkey')
    
    # 2. Удаляем все старые записи (так как нужно пересоздать связи)
    op.execute('DELETE FROM interactive_history')
    
    # 3. Меняем тип поля user_id с INTEGER на VARCHAR (String)
    op.alter_column('interactive_history', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    
    # 4. Создаем новую foreign key связь на user.user_id
    op.create_foreign_key('interactive_history_user_id_fkey', 'interactive_history', 'user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Удаляем новую foreign key связь
    op.drop_constraint('interactive_history_user_id_fkey', 'interactive_history', type_='foreignkey')
    
    # 2. Удаляем все записи
    op.execute('DELETE FROM interactive_history')
    
    # 3. Возвращаем тип поля user_id к INTEGER
    op.alter_column('interactive_history', 'user_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    
    # 4. Создаем старую foreign key связь на user.id
    op.create_foreign_key('interactive_history_user_id_fkey', 'interactive_history', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ### 