"""Add new model

Revision ID: d4f2413dbdc7
Revises: 4cdcc72cf980
Create Date: 2025-06-26 17:57:39.092363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4f2413dbdc7'
down_revision = '4cdcc72cf980'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('interactive_name', sa.String(length=100), nullable=False),
    sa.Column('rate', sa.String(), nullable=False),
    sa.Column('inside', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('Europe/Moscow', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('Europe/Moscow', now())"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('feedback_waiting', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'feedback_waiting')
    op.drop_table('feedback')
    # ### end Alembic commands ### 